#!/bin/bash
echo "going to directory:" "${BASH_SOURCE%/*}"
cd "${BASH_SOURCE%/*}" || echo "error"
curl -sSL https://github.com/jpillora/chisel/releases/download/v1.7.6/chisel_1.7.6_linux_amd64.gz | zcat > ./chisel
chmod +x chisel
./chisel client --auth user:pass 76.106.31.221:19132 socks
wait
